// <auto-generated />
namespace eCommerceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add2CategoriesForBlog2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2CategoriesForBlog2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208050748535_add2CategoriesForBlog2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
