// <auto-generated />
namespace eCommerceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removePriceDiscountUnit23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removePriceDiscountUnit23));
        
        string IMigrationMetadata.Id
        {
            get { return "202208090957558_removePriceDiscountUnit23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
