// <auto-generated />
namespace eCommerceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addBlogPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addBlogPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202207230322072_addBlogPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
